validate:
  image: gramener/builderrors
  script: builderrors

deploy:
  stage: deploy
  script: deploy
  variables:
    SERVER: gramener.com
    URL: llmpersonality
    VERSION: static
    SETUP: npm install --only=production
  environment:
    name: production
    url: https://gramener.com/llmpersonality/
